language: python
sudo: required
dist: trusty

python:
    - '2.7'
    - '3.5'
    - '3.6'

install:
    - pip install .
    - pip install nose2

script:
    - cd tests
    - nose2
    - cd ..

deploy:
    provider: pypi
    user: mmatl
    on:
        tags: true
        branch: master
    password:
        secure: VK1x0eiTgaxIC/OCsl4cknqyrtvd8g/YZYd7e+GBInzTA/5VPW85Ord9LinahrnDMlYIombG0fZDIU+MSMlcjNc+P5N9bbfwLuMWvqNLLn/5gUfCVXEhayXXC1mMHbl2qjAtwuiKHmgvGQGHBYT9x2qBhEpLp3DN45B9jsSiJvep6OQn9VW/7xyRp1wS9LKHy4C50eSE9yxzhBOcgQ+/Z5Cx/iHZF6ba+LJ+Zb+ciZbr+O7UcKQiTNA/lpZ/sMWvyRme0vdCmDaOddSI1Rff5KidkL8KD+vIRG0mP58JsFsfbnGfsrLOegxxJ1zg6J7HvZlMChDB1yaNHGAZ6+cZHTXnV4Hk3gRKHKCoVQmi15oY6lysprFDjlGEDRM5eb+EDjs75BBGvVCBqMuS5DQYeQhYWUAJ7UHyG9LX2PWvOZReodhzuWcVaFjyBB1VNcDIMDV0QjUThaMnG003Tqa+qV2o/6DMiRouiOezsPIvp8uBbF3cvMb2Mstdgoim4yUW+kI9nYk71arBAwO0825QyaZsKZ7m50G+ysplcVvq8dLeJ8pO43gYG6lUTkUMCnyOmZH7JIrTUD999vIrsdMqINc+QcQOVX8H4rR9knoCrTCI0Fc+KkZkqNvHiBiAx0NXsyi9zsfvF/AIwP4RcKVpkNcMqvPKzqtInz2Paw26KVA=

