language: python
sudo: required
dist: trusty
python:
- '2.7'
- '3.5'
- '3.6'
before_install:
- pip install --upgrade pip setuptools wheel
- pip install --only-binary=numpy,scipy numpy scipy
- pip install matplotlib==2.2.3
- pip install PyOpenGL
install:
- pip install .
- pip install nose2
script:
- cd tests
- nose2
- cd ..
deploy:
  provider: pypi
  skip_existing: true
  user: mmatl
  on:
    tags: true
    branch: master
  password:
    secure: VMn+8D74ayInKRyw1tYP7g1Ad/iG8co8hV0dAH1H3sCp90GVm0smvCH9hTXJsxKvMdHAKxGRlhbf7biZ8k2mP7pEOqan4J8rnAXSqkPlfBnt5UNvGwkLC+2cBYOHrM3bfyv9UtQvI4opyUkT4wSYhCM4C2+0r17wV8dotzGCfnoQF5EbmurBKa4fvX6gRxQQqDt9BBCJ8ScODMB6xo9taZJFscjbvXT791ue5OegPJodf5euttpYzeKY+bnTuxV1H2JqVgNZ2IgbplwoZvCmos5Mra9+QEFIY/M6hAuhudhSeP/as++mnqA9daIyipuePWaE9u+aENc80Q1xnpglfeJm39PcFTyG2SbeBOjKLiNpX1p0SWFgU8CxW5oL+vNfIIdh2lps3dl/jOf6gFupC0PSdEbIehHjY+tHt+cRY1VgqHhRfoFyACerihz0lxiA+Buev/6cfmKC9C8fwMM7KOlZBAknMSwvosdosL1uLb+EBG9rrmATgtoB3PkzEtRMEbs7aFQR+aCa9DQpfnRJDt14AScNqQAQl3vTnLSIDzvkL/gJNZm5ix3jgBLnvpxA7lLJRng10n7vTbvt8DELhSbSHXFj4Pw/aV8R/VjoVSIVIQO4ClLMpACuA75M4CTNAsWzklhXuX7c4H2ZliNJ5X+4WxskzBPI6xXiiXPTTvk=
  distributions: sdist bdist_wheel
notifications:
  email: false
