language: python
sudo: required
dist: trusty
python:
- '2.7'
- '3.5'
- '3.6'
before_install:
- pip install --upgrade pip setuptools wheel
- pip install --only-binary=numpy,scipy numpy scipy
- pip install matplotlib==2.2.3
- pip install PyOpenGL
install:
- pip install .
- pip install nose2
script:
- cd tests
- nose2
- cd ..
deploy:
  provider: pypi
  skip_existing: true
  user: mmatl
  on:
    tags: true
    branch: master
  password:
    secure: pAQuLX5y7m8H9OkWBXTvq611tfEL+y+DtpsJTE3oHUkV9v0QK4g75TZn4DFDY3Nan4vWzY7bdIG70dpJEa0HybDRRiSCY1c17K05T3dz1doc9ZdSb65MQrZI+mMTILfb34NbvoOQrlA/U0OGw0VTV9fIy+vfjOAT06iNb4dJA4NtPTz6OtqdHNt4eiiPqe7DUkEZLfHa7dxsClpBUzY7JEpmwfxwsawTfGSvbHzsKkchytpeCZ90bIXENalhVod9iUmRUygG6jZjzO+EsSLgQ26mOa0HkNHsWbqVv5LGAsUM6x4lDGo9ahfIMTDPMqSy8HEX1FhxACkjEyUJxrqOivwTYUhzgujQO+nLOFA6ZuM7VwYSa7iS5XxipJOkaRV8XQWtZqZ+ymQ0h8Nmh/AGmD/a4GCBaQ4NF9FdFHQtErS+QcQk3Dgmp26Xj1NUyxCGlYcjlQexE0+/8ehsaVgAYFF3y5ifJZg8xxBY+0VoyeE7YZqfwhtbWg98D4lssTRsye7FW5K+XN2fC0V1CAD0Cnrz2n8OMnLbRJrbfwwTs13iRwuGMIFyVGRLlb4G6VeWxPcvRQFuI8OrymP15EP9GMrBbKCCzcutAsP7CSsJNi07jbTPvDjqMqY7CUz5UJHvYmwa9CwTjqC+Au5lbheNCUmVh5bKIfKyVMl2CGEigYc=
  distributions: sdist bdist_wheel
notifications:
  email: false
