language: python
sudo: required
dist: trusty
python:
- '2.7'
- '3.5'
- '3.6'
before_install:
- pip install --upgrade pip setuptools wheel
- pip install --only-binary=numpy,scipy numpy scipy
- pip install PyOpenGL
install:
- pip install .
- pip install nose2
script:
- cd tests
- nose2
- cd ..
deploy:
  provider: pypi
  skip_existing: true
  user: mmatl
  on:
    tags: true
    branch: master
  password:
    secure: ebjxZc8clnS9nL0D5xHwbXHYmBnsqgJhXGKkUh8WhLESBiO1UURF+nbDH+1q59hJmjbMsK0UawAu65IZoSe+FCiNe56aoQ5/SmLeIgCDkRrPoy5LiciifCnYg0OTI/dS9Q3s9538SeNVEA/JS1/vsHE70VxJvT7zMg7mQLzXLZTEMZz8AYwqT9/LTfMazfst2keJTzR3BTByzeNLqUsNS7F2MjvzBJa87+4oxCUz0M6IvS3gQ9SmbdOlvZAavWS33SZVT8/V6Et9hNC5avBg9ZGdIlpqiYx5b6ZPff4oLr0dW+b/q7A4sOtQwyGasLt0fNZJXqd3eldjg81Ow6YJwqv+yn/xA8PpdVPtevCxwtbyGMmmUROSLhlvC5YMxufJ6ca4XG3Wyk4M1FqrH58B7XmnsFJV6wFR1arkuhtvsP5nDWNhaj6YU8Qh3gIY/tknszmRjsc9sUbA7+WHkElUFQacVEwOUvKjYvNsT42UkvUAE4ZvW8i3qeF/g6iUjbrZwkm3a43iFnnofwLWsHaOta0aNYgVUK1IwtVvFHOJxDpezdAINB9E9n8ekXuCujNMmljUC0zA1tyUymSQ6GGDmWqB7m6zZXHhTjjhQ0l8dC/My+ChBSEamOAOx/GE72UwkmTZRUlL1MpsptPBYkn5wrKGZM/QDui9YVG/mBbp2NM=
  distributions: sdist bdist_wheel
notifications:
  email: false
